apiVersion: v1
kind: Service
metadata:
  name: user-management-web
spec:
  type: NodePort
  selector:
    app: user-management-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
